version: '3'

services:
  # React App
  front-end:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run front-end:dev:docker
    ports:
      - 4201:4200

  # Nest App
  backend:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run backend:dev:docker
    ports:
      - 4310:3333 # API Entry port
      - 4311:4311 # Server Debugging port

  #Postgress
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: '3'
    ports:
      - '5438:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  keycloak:
    depends_on:
      - postgres
    container_name: local_keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: ${POSTGRESQL_DB}
      DB_USER: ${POSTGRESQL_USER}
      DB_PASSWORD: ${POSTGRESQL_PASS}
    image: jboss/keycloak:${KEYCLOAK_VERSION}
    ports:
      - '28080:8080'
    restart: unless-stopped

volumes:
  mono-node-modules: null
