version: '3'

services:
  # React App
  front-end:
    container_name: front-end
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run front-end:dev:docker
    ports:
      - 4200:4200

  # Nest App
  backend:
    container_name: backend
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: npm run backend:dev:docker
    ports:
      - 4310:3333 # API Entry port
      - 4311:4311 # Server Debugging port
      - 5556:5555
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: Todo
    volumes:
      - ./postgres-data:/var/lib/db/postgresql/data
    restart: unless-stopped

  keycloak:
    image: jboss/keycloak:latest
    container_name: keycloak
    depends_on:
      - postgres

    ports:
      - '28080:8080'
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: postgres
      DB_USER: ${PG_USER}
      DB_PASSWORD: ${PG_PASS}
      KEYCLOAK_USER: ${USER_KC}
      KEYCLOAK_PASSWORD: ${PASS_KC}
      KEYCLOAK_IMPORT: /tmp/realm-export.json
    volumes:
      - ./realm-export.json:/tmp/realm-export.json

    restart: unless-stopped

volumes:
  mono-node-modules: null
