version: '3'

services:
  # React App
  front-end:
    image: simkey84/platoontalk-front-end:dev
    command: npm run front-end:dev:docker
    ports:
      - 4200:4200

  # Nest App
  backend:
    image: simkey84/platoontalk-backend:dev
    ports:
      - 4310:3333 # API Entry port
      - 4311:4311 # Server Debugging port
      - 5556:5555
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Todo
    volumes:
      - ./postgres-data:/var/lib/db/postgresql/data
    restart: unless-stopped

  keycloak:
    depends_on:
      - postgres
    container_name: local_keycloak
    ports:
      - '28080:8080'

    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
    image: jboss/keycloak:latest

    restart: unless-stopped

volumes:
  mono-node-modules: null
